<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" />
    <PackageReference Include="DeviceDetector.NET" />
    <PackageReference Include="Handlebars.Net" />
    <PackageReference Include="SixLabors.ImageSharp" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Iam.DomainService\Iam.DomainService.csproj" />
    <ProjectReference Include="..\Mfa.DomainService\Mfa.DomainService.csproj" />
  </ItemGroup>

</Project>
