<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
	  <PackageReference Include="Grpc.AspNetCore" />
	  <PackageReference Include="BCrypt.Net-Next" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Captcha.Driver\Captcha.Driver.csproj" />
  </ItemGroup>
	
	<ItemGroup>
		<Protobuf Include="Protos\Users.proto" GrpcServices="Server" />
	</ItemGroup>

</Project>
