<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
	
		<Version>10.0.0-preview.1</Version>
		<PackageId>SeliseBlocks.OIDC.Driver</PackageId>
		<Authors>SeliseBlocks</Authors>
		<Company>SeliseBlocks</Company>
		<Description>Blocks OIDC Driver</Description>
		<IncludeBuildOutput>true</IncludeBuildOutput>
		<IncludeOutputAssemblies>true</IncludeOutputAssemblies>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageTags>Genesis, BlocksGenesis, SeliseBlocksGenesis, OIDC, Driver</PackageTags>
		<RepositoryUrl>https://github.com/SELISEdigitalplatforms/blocks-idp</RepositoryUrl>
	</PropertyGroup>


	<ItemGroup>
		<ProjectReference Include="../Authentication.DomainService/Authentication.DomainService.csproj">
			<PrivateAssets>all</PrivateAssets>
		</ProjectReference>
		<None Remove="bin\Release\net10.0\Authentication.DomainService.dll" />
		<None Include="$(OutputPath)Authentication.DomainService.dll" Pack="true" PackagePath="lib/net10.0/" />
	</ItemGroup>

</Project>
